import lowRisk from "./assets/images/lowrisk-icon.png";
import highRisk from "./assets/images/highrisk-icon.png";
import dollarIcon from "./assets/images/dollar-icon.png";
import statisticsIcon from "./assets/images/statistics-icon.png";
import viewIcon from "./assets/images/view-icon.png";
export const tableData = [
  {
    title: "AMZN",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    view: 200,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "Low Risk",
  },
  {
    title: "TSLA",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "High Risk",
  },
  {
    title: "ABQQ",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "Low Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "High Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "Low Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "High Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "High Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "Low Risk",
  },
  {
    title: "AMZN",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    view: 200,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "Low Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "High Risk",
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    riskImage: highRisk,
    riskType: "High Risk",
  },
  {
    title: "AMZN",
    view: 200,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "High Risk",
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    riskImage: lowRisk,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    riskType: "Low Risk",
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "Low Risk",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "Low Risk",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    riskImage: lowRisk,
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
    riskType: "Low Risk",
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    riskImage: lowRisk,
    riskType: "Low Risk",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
  },
  {
    title: "AMZN",
    view: 200,
    statistics: "-.25%",
    riskImage: highRisk,
    riskType: "Low Risk",
    titleImage: dollarIcon,
    statisticsImage: statisticsIcon,
    viewImage: viewIcon,
  },
];
